apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-svc
spec:
  selector:
    app: nginx-multitool
  ports:
    - name: nginx
      port: 80       
      targetPort: 9001 
    - name: multitool
      port: 8080
      targetPort: 9002
  type: ClusterIP